---
title: "4.4単回帰_Stan"
output: html_notebook
---

```{r}
d <- read.csv(file='stan2/RStanBook-master/chap04/input/data-salary.txt')
d
```


```{stan output.var=model45}
data {
  int N;
  real X[N];
  real Y[N];
}

parameters {
  real a;
  real b;
  real<lower=0> sigma;
}

model {
  for (n in 1:N) {
    //Y[n]が平均a + b*X[n]・標準偏差sigmaの正規分布から生成されたことを示す
    Y[n] ~ normal(a + b*X[n], sigma);
  }
}

```

```{r}
library(rstan)
data <- list(N=nrow(d), X=d$X, Y=d$Y)
fit <- sampling(model45, data=data, seed=1234)
```

```{r}
fit
```

年齢が一つ増えるごとに、基本年収が平均で21.97万円上がると解釈できる。

```{r}
library(ggmcmc)

#warmupとlp__を出力に含むように設定
ggmcmc(ggs(fit, inc_warmup=TRUE, stan_include_auxiliar=TRUE), file='matsuurastan/model4-5_fit-traceplot.pdf', plot='traceplot')
```

```{r}
ggmcmc(ggs(fit), file='matsuurastan/model4-5_fit-ggmcmc.pdf')
```

```{r}
ms <- rstan::extract(fit)
```


```{r}
ms$b
```

```{r}
quantile(ms$b, probs=c(0.025, 0.975))
```

ms$bは、全サンプルを保持している1次元array。
よって、quantile関数で簡単に95%区間を求めることができる。

```{r}
d_mcmc <- data.frame(a=ms$a, b=ms$b, sigma=ms$sigma)
head(d_mcmc)
```


```{r}
p_xy <- ggplot(d_mcmc, aes(x=a, y=b))
p_xy <- p_xy + geom_point(alpha=1/4, size=2, shape=1)
p_xy <- p_xy + scale_x_continuous(breaks=seq(-400, 200, 200), limits=c(-420, 210))
p_xy <- p_xy + scale_y_continuous(breaks=seq(15, 25, 5), limits=c(14.5, 29))

p_x <- ggplot(d_mcmc, aes(x=a))
p_x <- p_x + geom_histogram(aes(y=..density..))
p_x <- p_x + geom_density(alpha=0.3)
p_x <- p_x + scale_x_continuous(breaks=seq(-400, 200, 200), limits=c(-420, 210))

p_y <- ggplot(d_mcmc, aes(x=b))
p_y <- p_y + coord_flip()
p_y <- p_y + geom_histogram(aes(y=..density..))
p_y <- p_y + geom_density(alpha=0.3)
p_y <- p_y + scale_x_continuous(breaks=seq(15, 25, 5), limits=c(14.5, 29))

p_emp <- ggplot(data.frame(0, 0)) 

g_xy <- ggplotGrob(p_xy)
g_x <- ggplotGrob(p_x)
g_y <- ggplotGrob(p_y)
g_emp <- ggplotGrob(p_emp)

g1 <- cbind(g_x, g_emp, size='first')
g2 <- cbind(g_xy, g_y, size='first')
g <- rbind(g1, g2, size='first')
g$widths[1:3] <- grid::unit.pmax(g1$widths[1:3], g2$widths[1:3])
g$heights[7:12] <- g$widths[5:10] <- rep(unit(0.5,'mm'), 6)
g$heights[6] <- g$widths[11] <- unit(3,'cm')
#png(file='/Users/kojimajun/matsuurastan/fig4-7.png', res=300, w=1800, h=1800)
#grid::grid.draw(g)
#dev.off()
plot(g)
```

```{r}
N_mcmc <- length(ms$lp__)
y50_base <- ms$a + ms$b * 50
y50 <- rnorm(n=N_mcmc, mean=y50_base, sd=ms$sigma)
d_mcmc2 <- data.frame(a=ms$a, b=ms$b, sigma=ms$sigma, y50_base, y50)
```

前年齢分行う
```{r}
N_mcmc <- length(ms$lp__)
X_new <- 23:60
N_X <- length(X_new)

set.seed(1234)
y_base_mcmc <- as.data.frame(matrix(nrow=N_mcmc, ncol=N_X))
y_mcmc <- as.data.frame(matrix(nrow=N_mcmc, ncol=N_X))
for (i in 1:N_X) {
  y_base_mcmc[,i] <- ms$a + ms$b * X_new[i]
  y_mcmc[,i] <- rnorm(n=N_mcmc, mean=y_base_mcmc[,i], sd=ms$sigma)
}

```


```{r}
data.frame.quantile.mcmc <- function(x, y_mcmc, probs=c(2.5, 25, 50, 75, 97.5)/100) {
  qua <- apply(y_mcmc, 2, quantile, probs=probs)
  d <- data.frame(X=x, t(qua))
  colnames(d) <- c('X', paste0('p', probs*100))
  return(d)
}
ggplot.5quantile <- function(data, size=1) {
  qn <- colnames(data)[-1]
  p <- ggplot(data=data, aes(x=X, y=p50))
  p <- p + geom_ribbon(aes_string(ymin=qn[1], ymax=qn[5]), fill='black', alpha=1/6)
  p <- p + geom_ribbon(aes_string(ymin=qn[2], ymax=qn[4]), fill='black', alpha=2/6)
  p <- p + geom_line(size=size)
  return(p)
}
customize.ggplot.axis <- function(p) {
  p <- p + labs(x='X', y='Y')
  p <- p + scale_y_continuous(breaks=seq(from=200, to=1400, by=400))
  p <- p + coord_cartesian(xlim=c(22, 61), ylim=c(200, 1400))
  return(p)
}
d_est <- data.frame.quantile.mcmc(x=X_new, y_mcmc=y_base_mcmc)
p <- ggplot.5quantile(data=d_est)
p <- p + geom_point(data=d, aes(x=X, y=Y), shape=1, size=3)
p <- customize.ggplot.axis(p)
p
```

```{r}
d_est <- data.frame.quantile.mcmc(x=X_new, y_mcmc=y_mcmc)
p <- ggplot.5quantile(data=d_est)
p <- p + geom_point(data=d, aes(x=X, y=Y), shape=1, size=3)
p <- customize.ggplot.axis(p)
p
```

```{stan output.var=model44}

data {
  int N;
  real X[N];
  real Y[N];
  int N_new;
  real X_new[N_new];
}

parameters {
  real a;
  real b;
  real<lower=0> sigma;
}

transformed parameters {
  real y_base[N];
  for (n in 1:N)
    y_base[n] = a + b*X[n];
}

model {
  for (n in 1:N)
    Y[n] ~ normal(y_base[n], sigma);
}

generated quantities {
  real y_base_new[N_new];
  real y_new[N_new];
  for (n in 1:N_new) {
    y_base_new[n] = a + b*X_new[n];
    y_new[n] = normal_rng(y_base_new[n], sigma);
  }
}
```

```{r}
library(rstan)
library(ggplot2)

d <- read.csv(file='/Users/kojimajun/stan2/input/data-salary.txt')
X_new <- 23:60
data <- list(N=nrow(d), X=d$X, Y=d$Y, N_new=length(X_new), X_new=X_new)
fit <- sampling(model44, data=data, seed=1234)
ms <- rstan::extract(fit)
```

```{r}
data.frame.quantile.mcmc <- function(x, y_mcmc, probs=c(2.5, 25, 50, 75, 97.5)/100){
  #apply(X, MARGIN, 関数, ...):配列などのXのMARGIN(1=行,2=列,c(1,2)=全体)
  qua <- apply(y_mcmc, 2, quantile, probs=probs)
  #t():行列入れ替え
  d <- data.frame(X=x, t(qua))
  colnames(d) <- c('X', paste0('p', probs*100))
  return(d)
}

ggplot.5quantile <- function(data) {
  p <- ggplot(data=data, aes(x=X, y=p50))
  p <- p + geom_ribbon(aes(ymin=p2.5, ymax=p97.5), alpha=1/6)
  p <- p + geom_ribbon(aes(ymin=p25, ymax=p75), alpha=2/6)
  p <- p + geom_line(size=1)
  return(p)
}

customize.ggplot.axis <- function(p) {
  p <- p + labs(x='X', y='Y')
  p <- p + scale_y_continuous(breaks=seq(from=200, to=1400, by=400))
  p <- p + coord_cartesian(xlim=c(22, 61), ylim=c(200, 1400))
  return(p)
}

d_est <- data.frame.quantile.mcmc(x=X_new, y_mcmc=ms$y_base_new)
p <- ggplot.5quantile(data=d_est)
p <- p + geom_point(data=d, aes(x=X, y=Y), shape=1, size=3)
p <- customize.ggplot.axis(p)
p
```


```{r}
d_est <- data.frame.quantile.mcmc(x=X_new, y_mcmc=ms$y_new)
p <- ggplot.5quantile(data=d_est)
p <- p + geom_point(data=d, aes(x=X, y=Y), shape=1, size=3)
p <- customize.ggplot.axis(p)
p
```

